"""empty message

Revision ID: 7a742ca21e2a
Revises: ef9bccf989a5
Create Date: 2022-05-25 17:00:53.455778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a742ca21e2a'
down_revision = 'ef9bccf989a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('sample_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache')
    # ### end Alembic commands ###
