"""empty message

Revision ID: ef9bccf989a5
Revises: 2209a33970ab
Create Date: 2022-05-25 16:18:32.293127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef9bccf989a5'
down_revision = '2209a33970ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('sample_path', sa.String(length=255), nullable=False))
    op.add_column('sample', sa.Column('reverse_state', sa.Integer(), nullable=False))
    op.drop_column('sample', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('path', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('sample', 'reverse_state')
    op.drop_column('sample', 'sample_path')
    # ### end Alembic commands ###
